### ISSUE TITLE
Default value if no env is matched

### ISSUE THREAD

**Issue by FredyC** [chengjianhua/penv.macro#3]
Consider the following example...

```js
const SERVER_URL = env({
  production: 'https://production.example.com'
}) || 'https://development.example.com'
```

It might be somewhat nicer if we could do...

```js
const SERVER_URL = env({
  default: 'https://development.example.com',
  production: 'https://production.example.com'
})
```

It's useful when you know there is only a difference for one (or more) environment. Might be actually an alternative approach to #2. Thoughts?

I might try to provide PR if it sounds interesting.

**Comment by chengjianhua** [comment]
Thank you for your suggestions~ I missed out github notifications for a quite while.

#2 is about a more powerful approach to assign value to a group of variants.

But I guess I got your requirement, #4 may solve your problem, I think that's nicer. 

The `default` is a fallback, treat it as a normal key of variants is not appropriate enough.

I feel like to merge it, if you have a better idea, please comment it here, thx~

**Comment by chengjianhua** [comment]
Sorry to be late. I have published this as `penv.macro@0.4.0`.
